# Generated by Django 5.2 on 2025-04-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especializacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especializacoes',
            name='descricao',
            field=models.TextField(verbose_name=''),
        ),
    ]
